/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeonclient;

import engine.MessageInterpreter;
import game.Player;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import models.Command;
import models.CommandFactory;

/**
 *
 * @author Kurumin
 */
public class MainFrame extends javax.swing.JFrame {
   
    private HashMap<String, Command> cmdMap;
    private boolean shift, nameSet;
    private Player player;
    private MessageInterpreter gameStarter;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        shift = false;
        nameSet = false;
        player = new Player();
        player.setName("Unamed Player");
        initComponents();
        initGame();
    }
    
    public void initGame(){
        CommandFactory cmdfactory = new CommandFactory();
        Command cmdname = cmdfactory.defaultNameCommand();
        cmdMap = new HashMap<>();
        cmdMap.put(cmdname.getPrimary(), cmdname);
        dungeonChat.setText("[Dungeon Master]: Hello mortal! I need to know your name.\nPlease, type "+cmdname.getPrimary()+" to set a new name for you.\n\n");
        gameStarter = new MessageInterpreter();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        dungeonChat = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        playerChat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jSplitPane1.setBackground(new java.awt.Color(51, 51, 51));
        jSplitPane1.setDividerLocation(180);

        jSplitPane2.setDividerLocation(400);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        dungeonChat.setEditable(false);
        dungeonChat.setBackground(new java.awt.Color(0, 0, 0));
        dungeonChat.setColumns(20);
        dungeonChat.setForeground(new java.awt.Color(255, 255, 0));
        dungeonChat.setLineWrap(true);
        dungeonChat.setRows(1);
        jScrollPane6.setViewportView(dungeonChat);

        jSplitPane2.setTopComponent(jScrollPane6);

        playerChat.setBackground(new java.awt.Color(0, 0, 0));
        playerChat.setColumns(20);
        playerChat.setForeground(new java.awt.Color(255, 255, 0));
        playerChat.setLineWrap(true);
        playerChat.setRows(1);
        playerChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                playerChatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                playerChatKeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(playerChat);

        jSplitPane2.setRightComponent(jScrollPane7);

        jScrollPane1.setViewportView(jSplitPane2);

        jSplitPane1.setRightComponent(jScrollPane1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel2);

        jSplitPane1.setLeftComponent(jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playerChatKeyPressed
        //System.out.println(evt.getKeyCode());
        if(evt.getKeyCode() == KeyEvent.VK_SHIFT){
            shift = true;
        }
    }//GEN-LAST:event_playerChatKeyPressed

    private void playerChatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playerChatKeyReleased
        //System.out.println(evt.getKeyCode());
        if(evt.getKeyCode() == KeyEvent.VK_SHIFT){
            shift = false;
        }
        else if(shift == false && evt.getKeyCode() == KeyEvent.VK_ENTER){
            String chatContent = playerChat.getText();
            dungeonChat.append("["+player.getName()+"]: "+chatContent+"\n");
            playerChat.setText("");
            
            String result = gameStarter.interpretMessage(player, chatContent, cmdMap);
            dungeonChat.append("[Dungeon Master]: "+result+"\n\n");
        }
        else if(shift == true && evt.getKeyCode() == KeyEvent.VK_ENTER){
            playerChat.append("\n");
        }
    }//GEN-LAST:event_playerChatKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dungeonChat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea playerChat;
    // End of variables declaration//GEN-END:variables
}
