package client;

import com.bulenkov.darcula.DarculaLaf;
import game.Player;
import gui.Main;
import java.awt.event.KeyEvent;
import java.rmi.Naming;
import java.rmi.Remote;
import java.rmi.RemoteException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicLookAndFeel;
import models.Command;
import models.CommandFactory;
import server.DungeonServerInterface;

/**
 *
 * @author Kurumin
 */
public class ChatScreen extends javax.swing.JFrame {
   
    private HashMap<String, Command> cmdMap;
    private boolean shift, nameSet;
    private Player player;
    
    private Notification display;
    private DungeonServerInterface server;
    
    /**
     * Creates new form MainFrame
     */
    public ChatScreen() {
        shift = false;
        nameSet = false;
        player = new Player();
        player.setName("Unamed Player");
        initComponents();
        initGame();
    }
    
    public ChatScreen(Player plr) {
        this.shift = false;
        this.nameSet = false;
        this.player = plr;
        initComponents();
        initGame(); 
    }
    
    public void initGame(){
        CommandFactory cmdfactory = new CommandFactory();
        Command cmdname = cmdfactory.defaultNameCommand();
        cmdMap = new HashMap<>();
        cmdMap.put(cmdname.getPrimary(), cmdname);
        dungeonChat.setText("[Dungeon Master]: Hello mortal!\n\n");
        
        rmiConnection();
        login();
    }
    
    public void rmiConnection() {
        // ****************************************************************************************
        // Obter um socket Cliente RMI, invocacando o método lookup("rmichat") da classe Naming RMI
        // ****************************************************************************************        
        try {
            Remote remoteObject = Naming.lookup("rmi://localhost:1099/TIoDungeoneering");

            // Se interface esta OK
            if (remoteObject instanceof DungeonServerInterface) {
                // Obtem interface remota
                server = (DungeonServerInterface) remoteObject;

                // Instânciando a classe DisplayMessage() p/ q o ClienteCht possa usar 
                display = getRemoteImpl();
            } else {
                System.out.println("The server is not a TIoD Server.");
                System.exit(0);
            }
        } catch (Exception e) {
            System.out.println("Pesquisando exceção de RMI - Lookup Exception");
            e.printStackTrace();
            System.exit(0);
        };
    }
    
    private Notification getRemoteImpl() throws RemoteException {
        return new Remote_Implementation(player, dungeonChat);
    }
    
    private void login() {
        try {
            server.join(display, player.getName());
        } catch (RemoteException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        dungeonChat = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        playerChat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Theoretical Implications of Dungeoneering");
        setBackground(new java.awt.Color(0, 0, 0));

        jSplitPane1.setBackground(new java.awt.Color(51, 51, 51));
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setLastDividerLocation(200);

        jSplitPane2.setDividerLocation(400);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        dungeonChat.setEditable(false);
        dungeonChat.setColumns(20);
        dungeonChat.setForeground(new java.awt.Color(255, 255, 0));
        dungeonChat.setLineWrap(true);
        dungeonChat.setRows(1);
        jScrollPane6.setViewportView(dungeonChat);

        jSplitPane2.setTopComponent(jScrollPane6);

        playerChat.setColumns(20);
        playerChat.setForeground(new java.awt.Color(255, 255, 0));
        playerChat.setLineWrap(true);
        playerChat.setRows(1);
        playerChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                playerChatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                playerChatKeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(playerChat);

        jSplitPane2.setRightComponent(jScrollPane7);

        jScrollPane1.setViewportView(jSplitPane2);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel2);

        jSplitPane1.setLeftComponent(jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playerChatKeyPressed
        //System.out.println(evt.getKeyCode());
        if(evt.getKeyCode() == KeyEvent.VK_SHIFT){
            shift = true;
        }
    }//GEN-LAST:event_playerChatKeyPressed

    private void playerChatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playerChatKeyReleased
        //System.out.println(evt.getKeyCode());
        if(evt.getKeyCode() == KeyEvent.VK_SHIFT){
            shift = false;
        }
        else if(shift == false && evt.getKeyCode() == KeyEvent.VK_ENTER){
            String chatContent = playerChat.getText();
            dungeonChat.append("["+player.getName()+"]: "+chatContent+"\n");
            playerChat.setText("");
        }
        else if(shift == true && evt.getKeyCode() == KeyEvent.VK_ENTER){
            playerChat.append("\n");
        }
    }//GEN-LAST:event_playerChatKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            BasicLookAndFeel darcula = new DarculaLaf();
            UIManager.setLookAndFeel(darcula);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dungeonChat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea playerChat;
    // End of variables declaration//GEN-END:variables
}
